# Generated by Django 3.1.3 on 2020-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='products.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='parchases',
            field=models.ManyToManyField(blank=True, related_name='parchases', to='products.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishList',
            field=models.ManyToManyField(blank=True, related_name='wishList', to='products.Product'),
        ),
    ]
