# Generated by Django 3.1.2 on 2020-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaininginstock',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
