# Generated by Django 3.1.3 on 2020-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_wishlist'),
        ('users', '0008_auto_20201214_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parchases',
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='Cart', to='products.Cart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishList',
            field=models.ManyToManyField(blank=True, related_name='WishList', to='products.Wishlist'),
        ),
    ]
