# Generated by Django 3.1.3 on 2020-12-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201217_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishList',
            new_name='wishlist',
        ),
    ]
