# Generated by Django 3.1.3 on 2020-12-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201217_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='wishList',
        ),
    ]
