# Generated by Django 3.1.3 on 2020-12-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201217_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlists',
            new_name='wishlist',
        ),
    ]
