# Generated by Django 3.1.4 on 2020-12-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201227_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='orders', to='users.Order'),
        ),
    ]
