# Generated by Django 3.1.3 on 2020-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201227_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
