# Generated by Django 3.1.4 on 2020-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='user_orders', to='users.Order'),
        ),
    ]
