# Generated by Django 3.1.4 on 2020-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201229_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.FloatField(default=0.0),
        ),
    ]
