# Generated by Django 3.1.4 on 2020-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201224_1451'),
        ('users', '0029_auto_20201229_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='ordered_products', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='InCart',
        ),
    ]
