# Generated by Django 3.1.4 on 2020-12-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201224_1451'),
        ('users', '0032_auto_20201229_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='product',
        ),
        migrations.AddField(
            model_name='incart',
            name='product',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
