# Generated by Django 3.1.4 on 2020-12-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201224_1451'),
        ('users', '0033_auto_20201229_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='product',
        ),
        migrations.AddField(
            model_name='incart',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
