# Generated by Django 3.1.3 on 2020-12-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_orders'),
        ('users', '0037_auto_20201229_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shop', to='shop.shop'),
        ),
    ]
