# Generated by Django 3.1.3 on 2021-01-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_userlogouts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogouts',
            new_name='UserLogout',
        ),
    ]
