# Generated by Django 3.1.3 on 2021-01-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210107_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogout',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
