# Generated by Django 3.1.3 on 2021-01-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210107_0257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogout',
        ),
    ]
