# Generated by Django 3.1.5 on 2021-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=25)),
                ('activated', models.BooleanField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('coupon_type', models.CharField(choices=[('shop', 'shop'), ('event', 'event'), ('user', 'user')], default='shop', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('coupons', models.ManyToManyField(blank=True, default=None, related_name='shop_coupons', to='shop.Coupon')),
            ],
        ),
    ]
