# Generated by Django 3.1.4 on 2020-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=25)),
                ('activated', models.BooleanField()),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='coupons',
            field=models.ManyToManyField(default=None, null=True, to='shop.Coupon'),
        ),
    ]
