# Generated by Django 3.1.4 on 2020-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201226_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='coupons',
            field=models.ManyToManyField(default=None, to='shop.Coupon'),
        ),
    ]
