# Generated by Django 3.1.4 on 2020-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201227_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
