# Generated by Django 3.1.3 on 2020-12-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201227_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='coupons',
            field=models.ManyToManyField(default=None, related_name='shop_coupons', to='shop.Coupon'),
        ),
    ]
