# Generated by Django 3.1.3 on 2020-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20201229_1645'),
        ('shop', '0006_auto_20201228_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='orders',
            field=models.ManyToManyField(default=None, related_name='shop_orders', to='users.Order'),
        ),
    ]
