# Generated by Django 3.1.4 on 2021-01-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20201230_2153'),
        ('shop', '0007_shop_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='coupons',
            field=models.ManyToManyField(blank=True, default=None, related_name='shop_coupons', to='shop.Coupon'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='orders',
            field=models.ManyToManyField(blank=True, default=None, related_name='shop_orders', to='users.Order'),
        ),
    ]
