# Generated by Django 3.1.4 on 2021-01-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210101_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
