# Generated by Django 3.1.3 on 2021-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_coupon_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('shop', 'shop'), ('event', 'event'), ('user', 'user')], default='shop', max_length=5),
        ),
    ]
