# Generated by Django 3.1.3 on 2021-01-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_coupon_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
