# Generated by Django 3.1.3 on 2020-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('remaininginstock', models.PositiveSmallIntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
            ],
        ),
    ]
