# Generated by Django 3.1.3 on 2020-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201120_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='product_images/', width_field=500),
        ),
    ]
