# Generated by Django 3.1.3 on 2020-12-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201217_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='reviews',
        ),
    ]
