# Generated by Django 3.1.3 on 2020-12-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201217_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
    ]
