# Generated by Django 3.1.3 on 2021-01-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201224_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('mobile_phones', 'Mobile Phones'), ('electronics', 'Electronics'), ('home_applicanes', 'Home Appliances'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
