# Generated by Django 3.1.3 on 2021-01-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('tvs', 'TVs'), ('electronics', 'Electronics'), ('home_applicanes', 'Home Appliances'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
