# Generated by Django 3.1.5 on 2021-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210109_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vistits',
            field=models.IntegerField(default=0),
        ),
    ]
